version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck  # includes gosimple (merged in v2)
    - unused
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    errcheck:
      check-blank: true
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    presets: []  # equivalent to exclude-use-default: false

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hhiroshell/kube-booster

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
