apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - monitoring.yaml

configMapGenerator:
  - name: prometheus-config
    namespace: monitoring
    files:
      - prometheus.yml=prometheus.yml
      - rules.yaml=rules.yaml
    options:
      disableNameSuffixHash: true
  - name: grafana-dashboard-kube-booster
    namespace: monitoring
    files:
      - kube-booster.json=grafana-dashboard.json
    options:
      disableNameSuffixHash: true
